/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PublicLayoutRouteImport } from './routes/_publicLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as PublicLayoutIndexRouteImport } from './routes/_publicLayout/index'
import { Route as ApiTunnelRouteImport } from './routes/api/tunnel'
import { Route as AuthLayoutWarehousesRouteImport } from './routes/_authLayout/warehouses'
import { Route as AuthLayoutUsersRouteImport } from './routes/_authLayout/users'
import { Route as AuthLayoutSuppliersRouteImport } from './routes/_authLayout/suppliers'
import { Route as AuthLayoutStockMovementsRouteImport } from './routes/_authLayout/stock-movements'
import { Route as AuthLayoutSettingsRouteImport } from './routes/_authLayout/settings'
import { Route as AuthLayoutProductsRouteImport } from './routes/_authLayout/products'
import { Route as AuthLayoutDashboardRouteImport } from './routes/_authLayout/dashboard'
import { Route as AuthLayoutAuditLogsRouteImport } from './routes/_authLayout/audit-logs'
import { Route as AuthLayoutPurchaseRequestsIndexRouteImport } from './routes/_authLayout/purchase-requests/index'
import { Route as AuthLayoutPurchaseRequestsIdRouteImport } from './routes/_authLayout/purchase-requests/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutIndexRoute = PublicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ApiTunnelRoute = ApiTunnelRouteImport.update({
  id: '/api/tunnel',
  path: '/api/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutWarehousesRoute = AuthLayoutWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutUsersRoute = AuthLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSuppliersRoute = AuthLayoutSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutStockMovementsRoute =
  AuthLayoutStockMovementsRouteImport.update({
    id: '/stock-movements',
    path: '/stock-movements',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutSettingsRoute = AuthLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutProductsRoute = AuthLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutDashboardRoute = AuthLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuditLogsRoute = AuthLayoutAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutPurchaseRequestsIndexRoute =
  AuthLayoutPurchaseRequestsIndexRouteImport.update({
    id: '/purchase-requests/',
    path: '/purchase-requests/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutPurchaseRequestsIdRoute =
  AuthLayoutPurchaseRequestsIdRouteImport.update({
    id: '/purchase-requests/$id',
    path: '/purchase-requests/$id',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicLayoutIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/audit-logs': typeof AuthLayoutAuditLogsRoute
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/products': typeof AuthLayoutProductsRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/stock-movements': typeof AuthLayoutStockMovementsRoute
  '/suppliers': typeof AuthLayoutSuppliersRoute
  '/users': typeof AuthLayoutUsersRoute
  '/warehouses': typeof AuthLayoutWarehousesRoute
  '/api/tunnel': typeof ApiTunnelRoute
  '/purchase-requests/$id': typeof AuthLayoutPurchaseRequestsIdRoute
  '/purchase-requests/': typeof AuthLayoutPurchaseRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicLayoutIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/audit-logs': typeof AuthLayoutAuditLogsRoute
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/products': typeof AuthLayoutProductsRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/stock-movements': typeof AuthLayoutStockMovementsRoute
  '/suppliers': typeof AuthLayoutSuppliersRoute
  '/users': typeof AuthLayoutUsersRoute
  '/warehouses': typeof AuthLayoutWarehousesRoute
  '/api/tunnel': typeof ApiTunnelRoute
  '/purchase-requests/$id': typeof AuthLayoutPurchaseRequestsIdRoute
  '/purchase-requests': typeof AuthLayoutPurchaseRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_publicLayout': typeof PublicLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authLayout/audit-logs': typeof AuthLayoutAuditLogsRoute
  '/_authLayout/dashboard': typeof AuthLayoutDashboardRoute
  '/_authLayout/products': typeof AuthLayoutProductsRoute
  '/_authLayout/settings': typeof AuthLayoutSettingsRoute
  '/_authLayout/stock-movements': typeof AuthLayoutStockMovementsRoute
  '/_authLayout/suppliers': typeof AuthLayoutSuppliersRoute
  '/_authLayout/users': typeof AuthLayoutUsersRoute
  '/_authLayout/warehouses': typeof AuthLayoutWarehousesRoute
  '/api/tunnel': typeof ApiTunnelRoute
  '/_publicLayout/': typeof PublicLayoutIndexRoute
  '/_authLayout/purchase-requests/$id': typeof AuthLayoutPurchaseRequestsIdRoute
  '/_authLayout/purchase-requests/': typeof AuthLayoutPurchaseRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/audit-logs'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/stock-movements'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/api/tunnel'
    | '/purchase-requests/$id'
    | '/purchase-requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/audit-logs'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/stock-movements'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/api/tunnel'
    | '/purchase-requests/$id'
    | '/purchase-requests'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_publicLayout'
    | '/about'
    | '/login'
    | '/register'
    | '/_authLayout/audit-logs'
    | '/_authLayout/dashboard'
    | '/_authLayout/products'
    | '/_authLayout/settings'
    | '/_authLayout/stock-movements'
    | '/_authLayout/suppliers'
    | '/_authLayout/users'
    | '/_authLayout/warehouses'
    | '/api/tunnel'
    | '/_publicLayout/'
    | '/_authLayout/purchase-requests/$id'
    | '/_authLayout/purchase-requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiTunnelRoute: typeof ApiTunnelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publicLayout': {
      id: '/_publicLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publicLayout/': {
      id: '/_publicLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/api/tunnel': {
      id: '/api/tunnel'
      path: '/api/tunnel'
      fullPath: '/api/tunnel'
      preLoaderRoute: typeof ApiTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/warehouses': {
      id: '/_authLayout/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthLayoutWarehousesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/users': {
      id: '/_authLayout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthLayoutUsersRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/suppliers': {
      id: '/_authLayout/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthLayoutSuppliersRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/stock-movements': {
      id: '/_authLayout/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof AuthLayoutStockMovementsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/settings': {
      id: '/_authLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthLayoutSettingsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/products': {
      id: '/_authLayout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthLayoutProductsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/dashboard': {
      id: '/_authLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthLayoutDashboardRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/audit-logs': {
      id: '/_authLayout/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthLayoutAuditLogsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/purchase-requests/': {
      id: '/_authLayout/purchase-requests/'
      path: '/purchase-requests'
      fullPath: '/purchase-requests/'
      preLoaderRoute: typeof AuthLayoutPurchaseRequestsIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/purchase-requests/$id': {
      id: '/_authLayout/purchase-requests/$id'
      path: '/purchase-requests/$id'
      fullPath: '/purchase-requests/$id'
      preLoaderRoute: typeof AuthLayoutPurchaseRequestsIdRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutAuditLogsRoute: typeof AuthLayoutAuditLogsRoute
  AuthLayoutDashboardRoute: typeof AuthLayoutDashboardRoute
  AuthLayoutProductsRoute: typeof AuthLayoutProductsRoute
  AuthLayoutSettingsRoute: typeof AuthLayoutSettingsRoute
  AuthLayoutStockMovementsRoute: typeof AuthLayoutStockMovementsRoute
  AuthLayoutSuppliersRoute: typeof AuthLayoutSuppliersRoute
  AuthLayoutUsersRoute: typeof AuthLayoutUsersRoute
  AuthLayoutWarehousesRoute: typeof AuthLayoutWarehousesRoute
  AuthLayoutPurchaseRequestsIdRoute: typeof AuthLayoutPurchaseRequestsIdRoute
  AuthLayoutPurchaseRequestsIndexRoute: typeof AuthLayoutPurchaseRequestsIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAuditLogsRoute: AuthLayoutAuditLogsRoute,
  AuthLayoutDashboardRoute: AuthLayoutDashboardRoute,
  AuthLayoutProductsRoute: AuthLayoutProductsRoute,
  AuthLayoutSettingsRoute: AuthLayoutSettingsRoute,
  AuthLayoutStockMovementsRoute: AuthLayoutStockMovementsRoute,
  AuthLayoutSuppliersRoute: AuthLayoutSuppliersRoute,
  AuthLayoutUsersRoute: AuthLayoutUsersRoute,
  AuthLayoutWarehousesRoute: AuthLayoutWarehousesRoute,
  AuthLayoutPurchaseRequestsIdRoute: AuthLayoutPurchaseRequestsIdRoute,
  AuthLayoutPurchaseRequestsIndexRoute: AuthLayoutPurchaseRequestsIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLayoutIndexRoute: typeof PublicLayoutIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutIndexRoute: PublicLayoutIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiTunnelRoute: ApiTunnelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
